version: "3"

services:
  app:
    build:
      context: node
    container_name: app
    tty: true
    volumes:
      - ./node/:/usr/app/
    networks:
      - node-network
    ports:
      - 3000:3000
    entrypoint: >
      wait-for db:3306 -t 20 -- docker-entrypoint.sh
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
